version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:20  # Latest Node.js LTS image

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Clone the latest code from GitHub
      - setup_remote_docker:  # Enable Docker in CircleCI
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Linting
          command: npm run lint
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
