version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t ticket-management .
      - run:
          name: Install and Build Frontend
          command: |
            cd frontend
            npm install
            npm run build
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
