version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t ticket-management .
      - run:
          name: Run tests
          command: |
            cd frontend
            npm install
            npm test
            cd ../backend
            npm install
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
